CREATE DATABASE Boardgames;

GO

USE Boardgames;

CREATE TABLE Categories(
	Id INT IDENTITY PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL
);

CREATE TABLE Addresses(
	Id INT IDENTITY PRIMARY KEY,
	StreetName NVARCHAR(100) NOT NULL,
	StreetNumber INT NOT NULL,
	Town VARCHAR(30) NOT NULL,
	Country VARCHAR(50) NOT NULL,
	ZIP INT NOT NULL
);

CREATE TABLE Publishers(
	Id INT IDENTITY PRIMARY KEY,
	[Name] VARCHAR(30) NOT NULL,
	AddressId INT FOREIGN KEY REFERENCES Addresses(Id) NOT NULL,
	Website NVARCHAR(40) NULL,
	Phone NVARCHAR(20) NULL,
);

CREATE TABLE PlayersRanges(
	Id INT IDENTITY PRIMARY KEY,
	PlayersMin INT NOT NULL,
	PlayersMax INT NOT NULL,
);

CREATE TABLE Boardgames(
	Id INT IDENTITY PRIMARY KEY,
	[Name] NVARCHAR(30) NOT NULL,
	YearPublished INT NOT NULL,
	Rating DECIMAL (18,2) NOT NULL,
	CategoryId INT FOREIGN KEY REFERENCES Categories(Id) NOT NULL,
	PublisherId INT FOREIGN KEY REFERENCES Publishers(Id) NOT NULL,
	PlayersRangeId INT FOREIGN KEY REFERENCES PlayersRanges(Id) NOT NULL
);

CREATE TABLE Creators(
	Id INT IDENTITY PRIMARY KEY,
	FirstName NVARCHAR(30) NOT NULL,
	LastName NVARCHAR(30) NOT NULL,
	Email NVARCHAR(30) NOT NULL,
);

CREATE TABLE CreatorsBoardgames(
	PRIMARY KEY (CreatorId, BoardgameId),
	CreatorId INT FOREIGN KEY REFERENCES Creators(Id) NOT NULL,
	BoardgameId INT FOREIGN KEY REFERENCES Boardgames(Id) NOT NULL,
);