USE Minions;

CREATE TABLE Minions (
	Id INT IDENTITY (1,1) PRIMARY KEY,
	[Name] NVARCHAR (50) NOT NULL,
	Age INT NULL
);

CREATE TABLE Towns (
	Id INT IDENTITY (1,1) PRIMARY KEY,
	[Name] NVARCHAR (50) NOT NULL
);