CREATE DATABASE CarRentalDb;

GO

USE CarRentalDb

CREATE TABLE Categories(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	CategoryName NVARCHAR(50) NOT NULL,
	DailyRate DECIMAL(6,2) NOT NULL,
	WeeklyRate DECIMAL(6,2) NOT NULL,
	MonthlyRate DECIMAL(6,2) NOT NULL,
	WeekendRate DECIMAL(6,2) NOT NULL,
);

CREATE TABLE Cars(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	PlateNumber NVARCHAR(15) NOT NULL,
	Manufacturer NVARCHAR(25) NOT NULL,
	Model NVARCHAR(25) NOT NULL,
	CarYear TINYINT NOT NULL,
	CategoryId INT FOREIGN KEY REFERENCES Categories(Id),
	Doors DECIMAL(1,0),
	Picture VARBINARY CHECK (DATALENGTH(Picture) <= 2000000),
	Condition NVARCHAR(1000),
	Available BIT
);

CREATE TABLE Employees(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	Title NVARCHAR(50) NOT NULL,
	Notes NVARCHAR(100) NULL,
);