CREATE DATABASE SoftUniDb;

GO

USE SoftUniDb;

CREATE TABLE Towns(
	Id INT IDENTITY PRIMARY KEY,
	[Name] NVARCHAR(50) NOT NULL
);

CREATE TABLE Addresses(
	Id INT IDENTITY PRIMARY KEY,
	AddressText NVARCHAR(250) NOT NULL	,
	TownId INT FOREIGN KEY REFERENCES Towns(Id) NOT NULL
);

CREATE TABLE Departments(
	Id INT IDENTITY PRIMARY KEY,
	[Name] NVARCHAR(50) NOT NULL
);

CREATE TABLE Employees(
	Id INT IDENTITY PRIMARY KEY,
	FirstName NVARCHAR(50) NOT NULL,
	MiddleName NVARCHAR(50) NULL,
	LastName NVARCHAR(50) NOT NULL,
	JobTitle NVARCHAR(50) NOT NULL,
	DepartmentId INT FOREIGN KEY REFERENCES Departments(Id) NULL,
	HireDate DATE NOT NULL,
	Salary DECIMAL(18,2) NOT NULL,
	AddressId INT FOREIGN KEY REFERENCES Addresses(Id) NULL,
);



