USE master;

GO

CREATE TABLE  Passports(
	PassportID INT IDENTITY(101,1) PRIMARY KEY,
	PassportNumber VARCHAR(50) NOT NULL
);

CREATE TABLE Persons(
	PersonID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	FirstName NVARCHAR(50) NOT NULL,
	Salary DECIMAL(18,2) NOT NULL,
	PassportID INT FOREIGN KEY REFERENCES Passports(PassportID) UNIQUE NOT NULL
);

INSERT INTO Passports
VALUES
	('N34FG21B'),
	('ZE657QP2'),
	('K65LO4R7');

INSERT INTO Persons (FirstName, Salary, PassportID)
VALUES
	('Roberto', 43300, 102),
	('Tom', 56100, 103),
	('Yana', 60200, 101);



